#inventory.ini 

[webservers]
54.83.134.251 ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/ansible/j-keypair.pem

[local]
localhost ansible_connection=local


#Permissions on the PEM File:
Ensure that the permissions on your private key file are set correctly. The key file should have restrictive permissions (e.g., chmod 400 /home/ubuntu/ansible/j-keypair.pem).

#3. Run the Playbook: You can run your Ansible playbook with the following command:
ansible-playbook -i inventory.ini install-nginx.yml
